version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elk-wait:
    image: jwilder/dockerize
    command: dockerize -timeout 10m
                  -wait http://${HOST_IP}:5601/app/kibana

  filebeat:
    image: docker.elastic.co/beats/filebeat:5.5.1
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/lib/docker/volumes/bdd_xap-logs-volume/_data/wa:/mnt/log:ro']
    volumes:
      - ./filebeat/test-logs/:/mnt/log:ro
    depends_on: ['elasticsearch', 'logstash', 'kibana']

  # https://github.com/elastic/kibana/pull/10858
  dashboard-list:
    image: byrnedo/alpine-curl
    # curl --user <username>:<password> -XGET localhost:5601/api/kibana/dashboards/export?dashboard=<some-dashboard-uuid> > my-dashboards.json
    # command: ['sh', '-c', 'curl -XPUT http://$COUCHDB_SERVICE_HOST:$COUCHDB_SERVICE_PORT/_config/admins/$COUCHDB_USERNAME -d"\"$COUCHDB_PASSWORD"\"']
    command: -XGET http://${HOST_IP}:5601/api/kibana/dashboards/export?dashboard=33797130-97ae-11e7-aa10-79a79f2e360b > my-dashboards.json
    depends_on: ['kibana']    

  # https://github.com/elastic/kibana/pull/10858
  dashboard-export:
    image: byrnedo/alpine-curl
    # curl --user <username>:<password> -XGET localhost:5601/api/kibana/dashboards/export?dashboard=<some-dashboard-uuid> > my-dashboards.json
    # command: ['sh', '-c', 'curl -XPUT http://$COUCHDB_SERVICE_HOST:$COUCHDB_SERVICE_PORT/_config/admins/$COUCHDB_USERNAME -d"\"$COUCHDB_PASSWORD"\"']
    command: -XGET http://${HOST_IP}:5601/api/kibana/dashboards/export?dashboard=<some-dashboard-uuid> > my-dashboards.json
    # curl -XGET http://${HOST_IP}:5601/app/kibana/dashboards/export?dashboard=33797130-97ae-11e7-aa10-79a79f2e360b > my-dashboards.json
    depends_on: ['kibana']

  dashboard-import:
    image: byrnedo/alpine-curl
    # curl --user <username>:<password> -XGET localhost:5601/api/kibana/dashboards/export?dashboard=<some-dashboard-uuid> > my-dashboards.json
    # command: ['sh', '-c', 'curl -XPUT http://$COUCHDB_SERVICE_HOST:$COUCHDB_SERVICE_PORT/_config/admins/$COUCHDB_USERNAME -d"\"$COUCHDB_PASSWORD"\"']
    volumes:
      - ./filebeat/test-logs/:/mnt/log:ro    
    command: -XPOST http://${HOST_IP}:5601/api/kibana/dashboards/import -H 'kbn-xsrf:true' -H 'Content-type:application/json' -d @./my-dashboards.json
    depends_on: ['kibana']    

networks:

  elk:
    driver: bridge
